name: Renovate

on:
  schedule:
    - cron: '0 2 * * 6'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  renovate:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44.0.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: "['MrFabio/go-coding-challenges']"
          RENOVATE_USERNAME: renovate-release